name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '26.3'
          - '27.1'
          - '28.2'
          - '29.1'
          - 'snapshot'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Compile
        run: make compile

      - name: Tests
        run: make check
